### ISSUE TITLE
"Reported from in-game: Character won't move" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [Knightmarevive/TES#1]
tModLoader version: 0.11.6.2
 
| Mods:  | - | - |
| :--- | :--- | :--- |
| `AlchemistNPC Lite 1.7.1` | `Auto Trash 0.4.2` | `Boss Checklist 1.0.13` |
| `Boss Cursor 1.4.1` | `Calamity Mod (No Calamity Music) 1.4.3.1` | `Cheat Sheet 0.6.4` |
| `Athos's Class Overhaul 0.5.3` | `Elements Awoken 1.3.11` | `ExperienceAndClasses 1.3.13` |
| `Extensible Inventory 1.5.2` | `FastExtractinator 1.0` | `Beyond The Forgotten Ages 0.4.2.1` |
| `Mod Helpers 5.4.3` | `HERO's Mod 0.3.3` | `Lan's No More Banners 0.2` |
| `Anti-Grief Building-Locker 0.1.0.14` | `Even More Modifiers 0.1.2.3` | `Luiafk 1.0.0.130` |
| `Magic Storage 0.4.3.5` | `Max Stack Plus Extra 1.1.0.4` | `Modified Menu 0.1.1.29` |
| `OmniSwing 3.0` | `Recipe Browser 0.8.4.1` | `Reduced Grinding 5.7` |
| `Spirit Mod 1.3.5.4` | `TES Experience System 0.1.4.93` | `Thorium Mod 1.6.1.4` |
| `Audio4TES 0.1.0.6` | `Upgrade Equipment 1.0.3` | `VeinMiner 1.3.1` |
| `world tiles flag library 0.1.8.11` | - | - |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | False | True | 0 | 610 of 550 (500) | 70 of 20 | 0 |
 
**Player 1's (0) equipment:**
 
| Head | Body | Legs | Accessory 1 | Accessory 2 | Accessory 3 | Accessory 4 | Accessory 5 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Molten Helmet | Molten Breastplate | Molten Greaves | Idol of Darkness | Asterox | Celestial Idol | Heart of the Elements | Elysian Aegis |
 
Is day: True, Time of day/night: 47135.4, Elapsed half days: 1
 
World name: 1, world size: Small
 
World progress: Wall of Flesh killed
 
Items on ground: 6, Npcs active: 8
 
Player count: 1 (single-player)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 0
 
Frame skip mode: 2
 
Is screen maximized: False
 
Screen resolution: 1440 900
 
Quality style: 2
 
Background on: True
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
FrameworkVersion.Framework: NetFramework
 
FrameworkVersion.Version: 4.8
 
 
 
Recent error logs:
```
...
at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 300
at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 273
at Terraria.FNALaunch.Main(String[] args) in tModLoader\Terraria\FNALaunch.cs:line 30

[04:24:13] [22/INFO] [worldtilesflags]: Enabled Save Delayer
[04:24:13] [22/INFO] [worldtilesflags]: Reseting Save Stopwatch (Disabling) ...
[04:24:13] [22/INFO] [worldtilesflags]: Reseting Save Stopwatch... Done.
[04:25:13] [22/INFO] [worldtilesflags]: Reseting Save Stopwatch (Disabling) ...
[04:25:13] [22/INFO] [worldtilesflags]: Reseting Save Stopwatch... Done.
[04:26:13] [22/INFO] [worldtilesflags]: Reseting Save Stopwatch (Disabling) ...
[04:26:13] [22/INFO] [worldtilesflags]: Reseting Save Stopwatch... Done.
[04:27:13] [22/INFO] [worldtilesflags]: Reseting Save Stopwatch (Disabling) ...
[04:27:13] [22/INFO] [worldtilesflags]: Reseting Save Stopwatch... Done.
[04:28:13] [22/INFO] [worldtilesflags]: Reseting Save Stopwatch (Disabling) ...
[04:28:13] [22/INFO] [worldtilesflags]: Reseting Save Stopwatch... Done.
```
 
After testing each and every one of my mods one by one I've found that it's the new update to the mod 0.1.4.93 that makes any character stuck and doesn't matter what I do or try but enemies treat my characer as if they are still there but cannot deal damage and I can still move my character and open invintory and general menus, I also use TES Thorium and harder mode but I turned them off and off testing each time to make sure if was specifically this mod that was causing issues

**Comment by Knightmarevive** [comment]
it seems that

Elements Awoken 1.3.11

is not compatible with newest TES

Quote:
Jasper of the Dawn   17:21
As of now TES(0.1.4.85) doesnt work with Elements Awoken(1.3.11). As soon
as your game loades your character gets stuck and cant move. Sprites and
Music from other Mods also cease to work

SandBag  17:23
it's a change in Elements Awoken as it just updated

pt., 14 lut 2020 o 11:28 hamstar <notifications@github.com> napisał(a):
